# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :apk do
    gradle(task: "clean assembleRelease")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    upload_symbols_to_crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "My awesome app"
  lane :distribute do
    gradle(task: "clean assembleRelease")
    firebase_app_distribution(
      app: "1:889363668693:android:aeeb692aed00c85e590c5c",
      testers: "malliina123@gmail.com",
      release_notes: "Lots of cool stuff!",
      service_credentials_file: "api-5686430908194124552-499799-ab0012b9a06f.json",
      debug: true
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
