name: Test
on:
  pull_request:
    types:
      - opened
      - reopened
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macos-11
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
